[bin] update bump scripts to handle 3.0.0-fusion

diff --git a/bin/bump_nvidia_drivers b/bin/bump_nvidia_drivers
--- a/bin/bump_nvidia_drivers
+++ b/bin/bump_nvidia_drivers
@@ -1,13 +1,13 @@
 #!/bin/sh
 
-kernels="2.6.36-sabayon 2.6.37-sabayon 2.6.38-sabayon 2.6.39-sabayon 3.0.0-sabayon"
+kernels="2.6.36-sabayon 2.6.37-sabayon 2.6.38-sabayon 2.6.39-sabayon 3.0.0-sabayon 3.0.0-fusion"
 running_kernel="3.0.0-sabayon"
 packages="x11-drivers/nvidia-drivers::sabayon"
 
 # build for latest kernel
 KERNEL_DIR="/usr/src/linux-${running_kernel}" emerge $packages media-video/nvidia-settings::sabayon
 echo -5 | etc-update
-reagent update
+eit commit
 
 for kernel in $kernels; do
         if [ "${kernel}" = "${running_kernel}" ]; then
@@ -17,12 +17,8 @@ for kernel in $kernels; do
         KERNEL_DIR="/usr/src/linux-${kernel}" emerge -B ${packages} || ( echo "ouch unable to build" && exit 1 )
         built_pkgs=$(find /usr/portage/packages -name "*.tbz2" | xargs echo)
         [[ -z "${built_pkgs}" ]] && echo "ouch no kernel pkgs" && exit 2
-        reagent inject ${built_pkgs} || ( echo "ouch unable to inject" && exit 3 )
-        echo
-        reagent query tags ${kernel} -qv | sort
+        eit fit ${built_pkgs} || ( echo "ouch unable to inject" && exit 3 )
         echo
 done
 
-echo "Now you should remove old packages:"
-echo reagent repo remove `reagent query search ${packages} -qv | grep MY_OLD_VER | xargs echo`
-echo
+echo "Now you should remove old packages..."
