Revert "[bin] use --quick in bump_vbox eit usage"
This reverts commit 1ffbd515957bd0bf27a49643d7261275611bc7fd.

diff --git a/bin/bump_vbox b/bin/bump_vbox
--- a/bin/bump_vbox
+++ b/bin/bump_vbox
@@ -7,7 +7,7 @@ non_tagged_packages="virtualbox-bin"
 # build for latest kernel
 KERNEL_DIR="/usr/src/linux-${running_kernel}" emerge $packages ${non_tagged_packages}
 echo -5 | etc-update
-eit add ${packages} ${non_tagged_packages} --quick
+eit add ${packages} ${non_tagged_packages}
 
 for kernel in $kernels; do
         if [ "${kernel}" = "${running_kernel}" ]; then
@@ -17,7 +17,7 @@ for kernel in $kernels; do
         KERNEL_DIR="/usr/src/linux-${kernel}" emerge -B ${packages} || ( echo "ouch unable to build" && exit 1 )
         built_pkgs=$(find /usr/portage/packages -name "*.tbz2" | xargs echo)
         [[ -z "${built_pkgs}" ]] && echo "ouch no kernel pkgs" && exit 2
-        eit inject ${built_pkgs} --quick || ( echo "ouch unable to inject" && exit 3 )
+        eit inject ${built_pkgs} || ( echo "ouch unable to inject" && exit 3 )
         echo
         eit search "#${kernel}" -qv | sort | uniq
         echo
