[bin] make bump_misc usable on different systems
(don't require a script in a fixed location for sourcing)

diff --git a/bin/bump_misc b/bin/bump_misc
--- a/bin/bump_misc
+++ b/bin/bump_misc
@@ -3,7 +3,11 @@
 # script that makes it easier to bump split packages
 # (and perhaps other fun stuff)
 
-. /sabayon/bin/buildrc || exit 2
+if [ -e /sabayon/bin/buildrc ]; then
+	. /sabayon/bin/buildrc || exit 2
+else
+	echo "Warning: buildrc not found" >&2
+fi
 
 list="git [sub]version [tra]nsmission [qua]ssel"
 cmd="emerge -av"
